version: '2.3'

services:

  nginx:
    image: nginx:1.15-alpine
    mem_limit: 100m
    mem_reservation: 10m
    restart: always
    environment: 
      - WATCHTOWER_LABEL_ENABLE=false
    volumes:
      - ./data/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    
  angular:
    image: index.docker.io/wimtach2020/alphaglobalitangular
    mem_limit: 100m
    mem_reservation: 10m
    restart: always
    environment: 
      - TZ=America/Toronto
      - FORGET_ORGANIZATION=https://alphadev.ga:8181/api/v1/patients/forgotOrganization?e_Mail.address=
      - ALPHA_BACKEND_API=https://alphadev.ga:8181/api/v1/auth/authenticate
      - GET_PATIENTS_BACKEND=https://alphadev.ga:8181/api/v1/patients
      - BASE_URL=https://alphadev.ga:8181/api/v1

  certbot:
    image: certbot/certbot
    mem_limit: 100m
    mem_reservation: 10m
    restart: always
    environment: 
      - WATCHTOWER_LABEL_ENABLE=false
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    
# Added letsencrypt using this post: https://medium.com/@pentacent/nginx-and-lets-encrypt-with-docker-in-less-than-5-minutes-b4b8a60d3a71